import('./apps/react/ReactApp/myreactapp.js')
import('./apps/svelte/SvelteApp/mysvelteapp.js')
import('./apps/solid/SolidApp/mysolidapp.js')
import('./apps/svelte/Tester/mytester.js')
import('./apps/vue/VueApp/myvueapp.js')
