name: Next

on:
  push:
    branches: [ "next" ]
  pull_request:
    branches: [ "next" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org/
        cache: 'yarn'
    - run: yarn
    - run: yarn test
    - run: |
        BETA=$(yarn npm-version)
        cd lib
        npm publish $BETA
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
